export enum Category {
  PayToWin = "Pay To Win",
  SuperCompetitive = "Super Competitive",
  GreatPerformers = "Great Performers",
  DecentChoices = "Decent Choices",
  AlrightSituational = "Alright Situational",
  Avoid = "Avoid",
  IHateIt = "I hate it",
  PayToLose = "Pay To Lose",
}

export const colors: Record<Category, string> = {
  [Category.PayToWin]: "#8A2BE2",
  [Category.SuperCompetitive]: "#40E0D0",
  [Category.GreatPerformers]: "#006400",
  [Category.DecentChoices]: "#7CFC00",
  [Category.AlrightSituational]: "#FFFF00",
  [Category.Avoid]: "#FF8C00",
  [Category.IHateIt]: "#FF0000",
  [Category.PayToLose]: "#FF0000"
}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface TankDetails {}

export type IncompleteRecord<K extends string | number | symbol, V> = Partial<Record<K, V>>;

export type Year = 2022 | 2021 | 2020 | 2019;

export const tanksList = {
  "BZ 176": {},
  "Skoda T56": {},
  "Obj. 703-II": {},
  "Udarniy": {},
  "Borasque": {},
  "Iron Arnie": {},
  "EBR 75": {},
  "Vipera": {},
  "TS-5": {},
  "112": {},
  "Bisonte": {},
  "Chieftain Prototype": {},
  "Renegade": {},
  "IS3-A": {},
  "Obj. 252U Defender": {},
  "122 TM": {},
  "Astron Rex": {},
  "AMBT": {},
  "ELC EVEN 90": {},
  "LT 432": {},
  "TVP 100": {},
  "GSOR 1008": {},
  "TL7": {},
  "KV-4 KTTS": {},
  "WZ-114": {},
  "Somua SM": {},
  "E75 TS": {},
  "Nameless": {},
  "50TP Prototyp": {},
  "Emil 1951": {},
  "Tornvagn": {},
  "Charlemaine": {},
  "Calaban": {},
  "Gonzalo": {},
  "KV-5": {},
  "Type 59": {},
  "Kampfpanzer 07 RH": {},
  "Progetto 46": {},
  "CS-52 LIS": {},
  "Lansen C": {},
  "T44-100": {},
  "Obj 274a": {},
  "Char 75": {},
  "WZ-120-1 FT (T8)": {},
  "Turtle 1": {},
  "SU-130PM": {},
  "AMX M4 mle. 49 Liberté": {},
  "Strv K": {},
  "Caernavon AX": {},
  "T34": {},
  "M4Y": {},
  "Patriot": {},
  "Kreslavski": {},
  "T-34-3": {},
  "Alt Proto": {},
  "Lorraine": {},
  "M4A1 Revalorisé": {},
  "Mutz": {},
  "Eidelweise": {},
  "STA-2": {},
  "Centurion 5/1": {},
  "TL1 LPC": {},
  "Super Pershing": {},
  "T54 Mod 1": {},
  "Guard": {},
  "M41D": {},
  "M 41 90 mm": {},
  "HWK 30": {},
  "Senlac": {},
  "T92 LT": {},
  "WZ 120 (T9)": {},
  "AMX CDA": {},
  "Skorpion": {},
  "Jagdtiger 8,8 cm": {},
  "S1": {},
  "ISU-152K": {},
  "ISU-130": {},
  "FCM 50t": {},
  "VK 75.01k": {},
  "Lowe": {},
  "Chrystler K": {},
  "T77": {},
  "IS5": {},
  "Skoda T27": {},
  "AMX CDC": {},
  "FV4202": {},
  "T25 Pilot": {},
  "T42": {},
  "Jagdtiger Prototype": {},
  "T-103": {},
  "111": {},
  "Mauerbrecher": {},
  "59 Patton": {},
  "Panther 8,8 cm": {},
  "Räumpanzer": {},
  "Strv 81/Primo Victoria": {},
  "Chieftain/T95": {},
  "Ripper Patton": {},
  "Kanonen Jagdpanzer 105mm": {},
  "Kanonen Jagdpanzer 90mm": {},
  "Mutant": {},
  "Kyrovets": {},
  "IS6": {},
  "T95E2": {},
  "WZ-111": {},
  "Chimera": {},
  "WZ-112-2": {},
} as const satisfies Record<string, TankDetails>;

export type TankName = keyof typeof tanksList;

export type RatingsList = IncompleteRecord<Category, TankName[]>;

export const ratingsPerYear: IncompleteRecord<Year, RatingsList> = {
  2022: {
    [Category.PayToWin]: [
      "BZ 176",
      "Skoda T56",
      "Obj. 703-II",
      "Udarniy",
      "Borasque",
      "Iron Arnie",
      "EBR 75",
      "Vipera",
      "TS-5",
    ],
    [Category.SuperCompetitive]: [
      "112",
      "Bisonte",
      "Chieftain Prototype",
      "Renegade",
      "IS3-A",
      "Obj. 252U Defender",
      "122 TM",
      "Astron Rex",
      "AMBT",
      "ELC EVEN 90",
      "LT 432",
      "TVP 100",
      "GSOR 1008",
      "TL7",
      "KV-4 KTTS",
    ],
    [Category.GreatPerformers]: [
      "WZ-114",
      "Somua SM",
      "E75 TS",
      "Nameless",
      "50TP Prototyp",
      "Emil 1951",
      "Tornvagn",
      "Charlemaine",
      "Calaban",
      "Gonzalo",
      "KV-5",
      "Type 59",
      "Kampfpanzer 07 RH",
      "Progetto 46",
      "CS-52 LIS",
      "Lansen C",
      "T44-100",
      "Obj 274a",
      "Char 75",
      "WZ-120-1 FT (T8)",
      "Turtle 1",
      "SU-130PM",
    ],
    [Category.DecentChoices]: [
      "AMX M4 mle. 49 Liberté",
      "Strv K",
      "Caernavon AX",
      "T34",
      "M4Y",
      "Patriot",
      "Kreslavski",
      "T-34-3",
      "Alt Proto",
      "Lorraine",
      "M4A1 Revalorisé",
      "Mutz",
      "Eidelweise",
      "STA-2",
      "Centurion 5/1",
      "TL1 LPC",
      "Super Pershing",
      "T54 Mod 1",
      "Guard",
      "M41D",
      "M 41 90 mm",
      "HWK 30",
      "Senlac",
      "T92 LT",
      "WZ 120 (T9)",
      "AMX CDA",
      "Skorpion",
      "Jagdtiger 8,8 cm",
      "S1",
      "ISU-152K",
      "ISU-130",
    ],
    [Category.AlrightSituational]: [
      "FCM 50t",
      "VK 75.01k",
      "Lowe",
      "Chrystler K",
      "T77",
      "IS5",
      "Skoda T27",
      "AMX CDC",
      "FV4202",
      "T25 Pilot",
      "T42",
      "Jagdtiger Prototype",
      "T-103",
    ],
    [Category.Avoid]: [
      "111",
      "Mauerbrecher",
      "59 Patton",
      "Panther 8,8 cm",
      "Räumpanzer",
      "Strv 81/Primo Victoria",
      "Chieftain/T95",
      "Ripper Patton",
      "Kanonen Jagdpanzer 105mm",
      "Kanonen Jagdpanzer 90mm",
    ],
    [Category.IHateIt]: [
      "Mutant", // (Shouldn't ever have been sold)
      "Kyrovets", // (Cost way too much)
      "ELC EVEN 90", // (Because its toxic)
    ],
  },
  //Source Greg Brown
  2021: {
    [Category.PayToWin]: [
      "Skoda T56",
      "Renegade",
      "Obj. 703-II",
      "TS-5",
      "EBR 75",
      "Borasque",
    ],
    [Category.SuperCompetitive]: [
      "50TP Prototyp",
      "IS3-A",
      "122 TM",
      "Progetto 46",
      "Astron Rex",
      "Obj 274a",
      "GSOR 1008",
      "SU-130PM",
      "Turtle 1",
      "ELC EVEN 90",
      "LT 432",
    ],
    [Category.GreatPerformers]: [
      "WZ-112-2",
      "Somua SM",
      "E75 TS",
      "Emil 1951",
      "Tornvagn",
      "Charlemaine",
      "M4Y",
      "Kreslavski",
      "Obj. 252U Defender",
      "Type 59",
      "Skoda T27",
      "Alt Proto",
      "Kampfpanzer 07 RH",
      "CS-52 LIS",
      "T44-100",
      "WZ-120-1 FT (T8)",
      "Bisonte",
      "Skorpion",
      "M41D",

    ],
    [Category.DecentChoices]: [
      "FCM 50t",
      "AMX M4 mle. 49 Liberté",
      "VK 75.01k",
      "Lowe",
      "Calaban",
      "Caernavon AX",
      "Patriot",
      "IS5",
      "T-34-3",
      "Lorraine",
      "M4A1 Revalorisé",
      "Mutz",
      "STA-2",
      "Centurion 5/1",
      "Lansen C",
      "FV4202",
      "Chimera",
      "T25 Pilot",
      "TL1 LPC",
      "Super Pershing",
      "T54 Mod 1",
      "Guard",
      "AMX CDA",
      "ISU-152K",
      "M 41 90 mm",
      "HWK 30",
      "Senlac",
      "T77",
    ],
    [Category.AlrightSituational]: [
      "Chrystler K",
      "T34",
      "KV-5",
      "IS6",
      "AMX CDC",
      "Strv 81/Primo Victoria",
      "Jagdtiger 8,8 cm",
      "S1",
      "T92 LT",
      "T42",
    ],
    [Category.Avoid]: [
      "WZ-111",
      "Panther 8,8 cm",
      "Räumpanzer",
      "Kanonen Jagdpanzer 105mm",
      "T-103",
      "Ripper Patton",
    ],
    [Category.PayToLose]: [
      "Mauerbrecher",
      "Mutant",
      "59 Patton",
      "Kanonen Jagdpanzer 90mm",
    ],
  },
  //Shryquill - DOUBLECHECK
  2020: {
    [Category.PayToWin]: [
      "LT 432",
      "EBR 75",
      "Progetto 46",
      "Borasque",
      "TS-5",
    ],
    [Category.SuperCompetitive]: [
      "IS3-A",
      "Renegade",
      "Obj. 252U Defender",
      "Obj. 703-II",
      "Emil 1951",
      "Obj 274a",
      "T44-100",
      "Type 59",
      "Lansen C",
      "Turtle 1",
      "WZ-120-1 FT (T8)",
      "GSOR 1008",
      "SU-130PM",
    ],
    [Category.GreatPerformers]: [
      "IS5",
      "Lowe",
      "50TP Prototyp",
      "Somua SM",
      "Patriot",
      "T77",
      "Bisonte",
      "E75 TS",
      "ELC EVEN 90",
      "M 41 90 mm",
      "T54 Mod 1",
      "CS-52 LIS",
      "Lorraine",
      "Skorpion",
      "S1",

    ],
    [Category.DecentChoices]: [
      "IS6",
      "KV-5",
      "VK 75.01k", //Probs VK 75
      "112",
      "AMX M4 mle. 49 Liberté",
      "Caernavon AX",
      "FCM 50t",
      "HWK 30",
      "Mutz",
      "Skoda T27",
      "Strv 81/Primo Victoria",
      "TL1 LPC",
      "Centurion 5/1",
      "M4A1 Revalorisé",
      "ISU-152K",
    ],
    [Category.AlrightSituational]: [
      "Kreslavski",
      "T34",
      "Chrystler K",
      "T92 LT",
      "Guard",
      "Super Pershing",
      "T-34-3",
      "T42",
      "AMX CDC",
      "FV4202",
      "AMX CDA",
    ],
    [Category.Avoid]: [
      "WZ-111",
      "Senlac",
      "M41D",
      "Ripper Patton",
      "Räumpanzer",
      "Panther 8,8 cm",
      "STA-2",
      "T25 Pilot",
      "T-103",
      "Jagdtiger 8,8 cm",
      "Kanonen Jagdpanzer 105mm",
    ],
    [Category.PayToLose]: [
      "Mutant",
      "Mauerbrecher",
      "59 Patton",
      "Kanonen Jagdpanzer 90mm",
    ],
  },
  // Guima Channel
  2019: {
    [Category.PayToWin]: [
      "EBR 75",
      "Progetto 46",
      "TS-5",
      "Obj. 252U Defender",
      "LT 432",
    ],
    [Category.SuperCompetitive]: [
      "Type 59",
      "WZ-120-1 FT (T8)",
      "Lorraine",
      "ELC EVEN 90",
      "IS3-A",
      "SU-130PM",
      "Obj. 703-II",
    ],
    [Category.GreatPerformers]: [
      "112",
      "Somua SM",
      "Skorpion",
      "M 41 90 mm",
      "50TP Prototyp",
      "Lansen C",
      "Emil 1951",
      "Turtle 1",
      "Patriot",
      "Renegade",
      "IS5",
      "T44-100",
    ],
    [Category.DecentChoices]: [
      "WZ-111",
      "FCM 50t",
      "M4A1 Revalorisé",
      "AMX M4 mle. 49 Liberté",
      "HWK 30",
      "E75 TS",
      "Lowe",
      "S1",
      "FV4202",
      "Caernavon AX",
      "Centurion 5/1",
      "Chimera",
      "TL1 LPC",
      "T54 Mod 1",
      "Guard",
    ],
    [Category.AlrightSituational]: [
      "T-34-3",
      "Skoda T27",
      "Mutz",
      "VK 75.01k",
      "Räumpanzer",
      "Senlac",
      "Chrystler K",
      "T34",
      "Super Pershing",
      "T92 LT",
      "T-103",
      "KV-5",
      "IS6",
    ],
    [Category.Avoid]: [
      "AMX CDC",
      "AMX CDA",
      "Kanonen Jagdpanzer 105mm",
      "Jagdtiger 8,8 cm",
      "STA-2",
      "Strv 81/Primo Victoria",
      "Chieftain/T95",
      "T25 Pilot",
      "T95E2",
      "ISU-130",
      "Kreslavski",
    ],
    [Category.PayToLose]: [
      "59 Patton",
      "M41D",
      "Panther 8,8 cm",
      "Kanonen Jagdpanzer 90mm",
      "Mauerbrecher",
      "Mutant",
    ],
  },
}